### ISSUE TITLE
Reason for running on edge instead of stable?

### ISSUE THREAD

**Issue by andyshinn** [mini-containers/base#3]
Curious about two things:

* Why running on edge? Edge is broken for at least `mysql-client` (my test case for mini/base was a super small MySQL client). However, that works fine when rebuilt on v3.1.
* Why extra layers for maintainer and `apk upgrade`? The upgrade would be better left to the user if they wanted to. Not sure if there is a need to upgrade assuming you just build the image. Also, adding extra layers for stuff like `MAINTAINER` seems kind of against the spirit of something trying to be minimal.

Just my $0.02. I'd love to try and use this as my go to for minimal containers. But don't really want to really on edge and would much prefer a base on stable or even better, tags to choose my version.

I'd be happy to make a pull request if you agree on these points. Thanks for your work on this so far!

**Comment by luislavena** [comment]
@andyshinn thank you for your questions, very good ones!

> Why running on edge?

The decision of usage of edge is to be able to access latest packages on it that are not part of stable. For example PostgreSQL 9.4 or latest Redis.

> Why extra layers for maintainer and apk upgrade?

Well, `MAINTAINER` is there because... well, I do maintain it, right? :smile:

Honestly maintainer does not add megabytes to the size of the image that is downloaded, is just metadata.

The upgrade and the installation of some basic packages was required when `rootfs` was done my other (see when rootfs was introduced). Things like musl gets updated every now and then.

I believe now it is not required since rootfs has been build recently. However, from time to time we should perform a rebuild of rootfs.

Since I'm using automated builds, I think maintaining a separate `stable-3.1` branch that contains latest stable version (instead of edge) is possible.

Would that work for you?

Cheers.

**Comment by luislavena** [comment]
@andyshinn link to rootfs change: #1

**Comment by andyshinn** [comment]
I didn't realize the rootfs wasn't being built every Docker image build. That makes a little more sense now. A `stable-3.1` tag would definitely work. I'm also playing with the `mkimage.sh` script to build my own customized version. I appreciate the explanations!

**Comment by luislavena** [comment]
@andyshinn seems you took inspiration from mini/base and put into your own thing:

https://github.com/gliderlabs/docker-alpine

Seems definitely `MAINTAINER` was itching you :smile: 

Are you still interested in these changes or can I close this issue?

Please let me know.

**Comment by progrium** [comment]
I think `MAINTAINER` was not the issue, but that it was using up an extra
layer for no significant reason. We've gotten quite meticulous about
minimal containers, and especially for base images, there should be as few
layers as possible.

Also, we wanted to open up and include the build process to run on
CircleCI. Maybe you can take advantage of some of these changes, but our
assumption is that mini/base is really used for your own projects and not
as much as a general purpose base image. If that's not the case, then lets
work together to make a really solid, minimal Alpine base that we can later
add to the Docker standard library so someday soon people can do just
`docker pull alpine` or `FROM alpine`.

On Sat, Jan 24, 2015 at 9:41 AM, Luis Lavena <notifications@github.com>
wrote:

> @andyshinn <https://github.com/andyshinn> seems you took inspiration from
> mini/base and put into your own thing:
>
> https://github.com/gliderlabs/docker-alpine
>
> Seems definitely MAINTAINER was itching you [image: :smile:]
>
> Are you still interested in these changes or can I close this issue?
>
> Please let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mini-containers/base/issues/3#issuecomment-71322952>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by luislavena** [comment]
@progrium thanks for your response, really appreciate you took the time.

`mini/base` is the building block of several containers we have been using to run development services (as you can see part of mini-containers organization) and also for other stuff, like builders, binary RubyGems compilers and other stuff.

We are also using it to base tailored containers for Ruby which we are thinking release too.

While I have no particular interest if this gets *vetted* as official image or not, I left a comment on my concerns about lack of attribution for `mkimage.sh`:

https://github.com/gliderlabs/docker-alpine/commit/7155b54cc87d89a9b7b19a8eb82c673104bcbd58#commitcomment-9428403

Specially if you read this project README and #1 request for permission.

If you read the README, will notice that the idea of the project was serve as foundation for others to build on top, so definitely I'm interested in anything that can improve that for others (aka: collaboration).

As for CircleCI usage, I had the assumption *automated* builds were better for users, but seems that is no longer the case (or the recommendation). Taking that in consideration we might change the way we build things. Thanks for sharing that information.

Once again, I appreciate you took the time to respond; will review what you guys have shared and probably introduce some of those modifications to mini/base myself, if is OK with you.

Cheers.
