### ISSUE TITLE
Alpine v3.4 is out

### ISSUE THREAD

**Issue by nikolay** [mini-containers/base#7]
http://alpinelinux.org/posts/Alpine-3.4.0-released.html

**Comment by luislavena** [comment]
Hello @nikolay, thank you for submitting this.

I might not be able to tackle this in the upcoming days, but feel free to clone and attempt to build the image by looking at the past changes as reference (that will also help us know if this process can be reproduced by others or that it needs more documentation)

Will update this issue once have the availability.

Cheers.

**Comment by nikolay** [comment]
@luislavena I will try, thanks! 👍

**Comment by luislavena** [comment]
Hello,

Latest base is based on `v3.6`, as part of #9 merge.

You can use this updated version or use official `alpine` image instead.

Closing now.

Cheers.

**Comment by nikolay** [comment]
Thank you, @luislavena!
